# Generated by Django 6.0.1 on 2026-02-06 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='User ID (ms users)')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative for outflows, positive for inflows', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('RECARGA', 'Recarga de Saldo'), ('REEMBOLSO', 'Reembolso'), ('COBRO_CREAR_CLASE', 'Comisión Creación Clase'), ('PAGO_RESERVA', 'Pago de Reserva'), ('RETIRO', 'Retiro de Fondos')], max_length=30)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('payment_method', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA', 'Tarjeta Crédito/Débito'), ('SALDO', 'Saldo Interno'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTRO', 'Otro')], default='OTRO', help_text='Medio por el cual entró o salió el dinero', max_length=20)),
                ('reference_source', models.CharField(blank=True, max_length=50, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='ID externo (Reserva ID, Clase ID, etc)', max_length=100, null=True)),
                ('info', models.JSONField(blank=True, default=dict, help_text='Detalles extra (CCI, Banco, Errores, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.wallet')),
            ],
        ),
    ]
