# Generated by Django 6.0.1 on 2026-02-05 19:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorRatingCache',
            fields=[
                ('profesor_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('sum_ponderada', models.DecimalField(decimal_places=6, max_digits=18)),
                ('sum_pesos', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_calificaciones', models.PositiveIntegerField()),
                ('avg_estrellas', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profesor_rating_cache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('carrera', models.CharField(max_length=120)),
                ('ciclo_relativo', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'materia',
                'indexes': [models.Index(fields=['nombre'], name='ix_materia_nombre')],
                'constraints': [models.UniqueConstraint(fields=('carrera', 'nombre'), name='uq_materia_carrera_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PUBLICADA', 'Publicada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada'), ('EN_PROGRESO', 'En progreso')], default='PUBLICADA', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_participantes', models.PositiveIntegerField(default=1)),
                ('link_zoom', models.URLField(blank=True)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='core.materia')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.PositiveBigIntegerField()),
                ('opinion', models.TextField(blank=True)),
                ('estrellas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.clase')),
            ],
            options={
                'db_table': 'calificacion',
                'indexes': [models.Index(fields=['clase'], name='ix_calificacion_clase'), models.Index(fields=['alumno_id'], name='ix_calificacion_alumno')],
                'constraints': [models.UniqueConstraint(fields=('alumno_id', 'clase'), name='uq_calificacion_alumno_clase')],
            },
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.clase')),
            ],
            options={
                'db_table': 'clase_horario',
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='ck_horario_horas_validas')],
            },
        ),
        migrations.CreateModel(
            name='Crea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_id', models.PositiveBigIntegerField()),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('comision_por_curso', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rol', models.CharField(choices=[('CREADOR', 'Creador'), ('COHOST', 'Co-host'), ('ASISTENTE', 'Asistente')], default='CREADOR', max_length=20)),
                ('porcentaje_reparto', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creadores', to='core.clase')),
            ],
            options={
                'db_table': 'crea',
                'indexes': [models.Index(fields=['clase'], name='ix_crea_clase'), models.Index(fields=['profesor_id'], name='ix_crea_profesor')],
                'constraints': [models.UniqueConstraint(fields=('profesor_id', 'clase'), name='uq_crea_profesor_clase')],
            },
        ),
        migrations.CreateModel(
            name='Llevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_id', models.PositiveBigIntegerField()),
                ('promedio_ponderado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ciclo_cursado', models.PositiveSmallIntegerField()),
                ('profesor', models.CharField(blank=True, max_length=120)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llevos', to='core.materia')),
            ],
            options={
                'db_table': 'llevo',
                'indexes': [models.Index(fields=['materia'], name='ix_llevo_materia'), models.Index(fields=['profesor_id'], name='ix_llevo_profesor')],
                'constraints': [models.UniqueConstraint(fields=('profesor_id', 'materia'), name='uq_llevo_profesor_materia')],
            },
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['materia', 'estado', 'fecha_fin', 'fecha_inicio'], name='ix_clase_m_e_ff_fi'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__lte', models.F('fecha_fin'))), name='ck_clase_rango_fechas'),
        ),
    ]
