# Generated by Django 6.0.1 on 2026-01-31 21:34
from django.db import migrations

CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS profesor_rating_cache (
  profesor_id BIGINT UNSIGNED NOT NULL,
  sum_ponderada DECIMAL(18,6) NOT NULL DEFAULT 0,
  sum_pesos     DECIMAL(18,6) NOT NULL DEFAULT 0,
  total_calificaciones INT NOT NULL DEFAULT 0,
  avg_estrellas DECIMAL(6,3) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (profesor_id)
) ENGINE=InnoDB;
"""

DROP_TABLE = "DROP TABLE IF EXISTS profesor_rating_cache;"

# --- Trigger INSERT: suma aportes a 1..N profesores de esa clase (ponderado por porcentaje_reparto)
TRG_AI = """
DROP TRIGGER IF EXISTS trg_calificacion_ai;

CREATE TRIGGER trg_calificacion_ai
AFTER INSERT ON calificacion
FOR EACH ROW
BEGIN
  IF EXISTS (
    SELECT 1
    FROM clase
    WHERE id = NEW.clase_id
      AND estado = 'FINALIZADA'
  ) THEN

    INSERT INTO profesor_rating_cache (
      profesor_id, sum_ponderada, sum_pesos, total_calificaciones, avg_estrellas
    )
    SELECT
      cr.profesor_id,
      (NEW.estrellas * (cr.porcentaje_reparto / 100.000000)) AS sum_ponderada,
      (cr.porcentaje_reparto / 100.000000)                  AS sum_pesos,
      1                                                     AS total_calificaciones,
      NEW.estrellas                                         AS avg_estrellas
    FROM crea cr
    WHERE cr.clase_id = NEW.clase_id
    ON DUPLICATE KEY UPDATE
      -- acumula
      sum_ponderada = sum_ponderada + VALUES(sum_ponderada),
      sum_pesos     = sum_pesos     + VALUES(sum_pesos),
      total_calificaciones = total_calificaciones + 1,
      -- promedio con “nuevo_sum / nuevo_peso”
      avg_estrellas =
        (sum_ponderada ) / NULLIF(sum_pesos, 0);

  END IF;
END;
"""

# --- Trigger DELETE: revierte aportes
TRG_AD = """
DROP TRIGGER IF EXISTS trg_calificacion_ad;

CREATE TRIGGER trg_calificacion_ad
AFTER DELETE ON calificacion
FOR EACH ROW
BEGIN
  IF EXISTS (
    SELECT 1
    FROM clase
    WHERE id = OLD.clase_id
      AND estado = 'FINALIZADA'
  ) THEN

    UPDATE profesor_rating_cache pr
    JOIN (
      SELECT
        profesor_id,
        (OLD.estrellas * (porcentaje_reparto / 100.000000)) AS delta_sum,
        (porcentaje_reparto / 100.000000)                   AS delta_peso
      FROM crea
      WHERE clase_id = OLD.clase_id
    ) t ON t.profesor_id = pr.profesor_id
    SET
      pr.sum_ponderada = pr.sum_ponderada - t.delta_sum,
      pr.sum_pesos     = pr.sum_pesos     - t.delta_peso,
      pr.total_calificaciones = pr.total_calificaciones - 1,
      -- promedio con “nuevo_sum / nuevo_peso”
      pr.avg_estrellas =
        (pr.sum_ponderada - t.delta_sum) / NULLIF((pr.sum_pesos - t.delta_peso), 0);

    DELETE FROM profesor_rating_cache
    WHERE profesor_id IN (SELECT profesor_id FROM crea WHERE clase_id = OLD.clase_id)
      AND (total_calificaciones <= 0 OR sum_pesos <= 0);

  END IF;
END;
"""


DROP_TRG_AI = "DROP TRIGGER IF EXISTS trg_calificacion_ai;"
DROP_TRG_AD = "DROP TRIGGER IF EXISTS trg_calificacion_ad;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(CREATE_TABLE, reverse_sql=DROP_TABLE),
        migrations.RunSQL(TRG_AI, reverse_sql=DROP_TRG_AI),
        migrations.RunSQL(TRG_AD, reverse_sql=DROP_TRG_AD),
    ]
