# Generated by Django 6.0.1 on 2026-02-07 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.PositiveBigIntegerField()),
                ('clase_id', models.PositiveBigIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('monto_acordado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comision_por_alumno', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp_creado', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reserva',
                'indexes': [models.Index(fields=['alumno_id', 'timestamp_creado'], name='ix_reserva_alumno_ts'), models.Index(fields=['clase_id', 'timestamp_creado'], name='ix_reserva_clase_ts'), models.Index(fields=['estado'], name='ix_reserva_estado')],
                'constraints': [models.UniqueConstraint(fields=('alumno_id', 'clase_id'), name='uq_reserva_alumno_clase')],
            },
        ),
        migrations.CreateModel(
            name='Negociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_propuesto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('propuesto_por', models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociaciones', to='core.reserva')),
            ],
            options={
                'db_table': 'negociacion',
                'indexes': [models.Index(fields=['reserva', 'estado', 'created_at'], name='ix_nego_reserva_estado_ts')],
            },
        ),
    ]
